class_name Types

enum GemType { RED, BLUE, GREEN, YELLOW, PURPLE, ORANGE }
enum BoosterType { H_ROCKET, V_ROCKET, TNT, LIGHT_BALL, MISSILE }
enum CellType { NORMAL, SPAWNER, BLANK, SHIFTER }
enum ObstacleType { NONE, STONE, FENCE, GRASS, CHAIN, GENERATOR, DOWNWARD }
enum MergeType {
	CROSS, BIG_ROCKET, MEGA_EXPLOSION, ALL_BOARD,
	COLOR_ROCKET, COLOR_TNT, COLOR_MISSILE,
	TRIPLE_MISSILE, MISSILE_ROCKET, MISSILE_TNT
}

const BOARD_COLS := 8
const BOARD_ROWS := 10
const CELL_SIZE := 44
const GEM_TYPES_COUNT := 6
const MATCH_MIN := 3

const BOARD_OFFSET_X := (390 - BOARD_COLS * CELL_SIZE) / 2
const BOARD_OFFSET_Y := 120
